### ISSUE TITLE
Crash on robot.ed.classify(...)

### ISSUE THREAD

**Issue by LFBFerreira** [tue-robotics/ed_perception#18]
Doesn't happen all the time, but sometimes it crashes on the classifying stage. I am using it for people recognition.

```Bash
[INFO] [WallTime: 1452344746.179564] 'I need an operator, please stand in front of me.'
[INFO] [WallTime: 1452344746.260010] State machine transitioning 'SAY_WAITING_OPERATOR':'spoken'-->'LOOK_AT_OPERATOR'
Waiting for 4 seconds to reach target ...
[ERROR] [WallTime: 1452344749.253846] InvalidUserCodeError: Could not execute state 'LOOK_AT_OPERATOR' of type '<robot_smach_states.human_interaction.human_interaction.LookAtPersonInFront object at 0x7fb81f4cb490>': Traceback (most recent call last):
  File "/home/amigo/ros/indigo/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/indigo/system/src/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py", line 442, in execute
    desgnResult = scanForHuman(self.robot)
  File "/home/amigo/ros/indigo/system/src/robot_smach_states/src/robot_smach_states/human_interaction/human_interaction.py", line 587, in scanForHuman
    res_classify = robot.ed.classify(entity_list)
  File "/home/amigo/ros/indigo/system/src/robot_skills/src/robot_skills/world_model_ed.py", line 281, in classify
    res = self._ed_classify_srv(ids = ids, property = property, perception_models_path=path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 696, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
ServiceException: service [/amigo/ed/classify] responded with an error: /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/array.cpp:2482: error: (-206) Unrecognized or unsupported array type in function cvGetMat


[ERROR] [WallTime: 1452344749.254246] State 'WAIT_PERSON_CONTAINER' failed to execute.
An exception occured
```

**Comment by reinzor** [comment]
Is this fixed?
