### ISSUE TITLE
Storing groceries crash

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/ed_perception#27]
Succesfully stored '/home/amigo/ed/kinect/2017-09-26/shelf5_bookcase/2017-09-26-21-02-24_rgb.png'
/home/amigo/ros/kinetic/system/devel/lib/ed/ed(_Z13signalHandleri+0x558)[0x4da144]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7faed7b8f4b0]
/home/amigo/ros/kinetic/system/devel/.private/ed/lib/libed_io.so(_ZN2ed9ImageMask14const_iteratorC1EPKN2cv6Point_IiEEi+0x25)[0x7faeda9d4cdd]
/home/amigo/ros/kinetic/system/devel/.private/ed/lib/libed_io.so(_ZNK2ed9ImageMask3endEv+0x38)[0x7faeda9d4f6c]
/home/amigo/ros/kinetic/system/devel/.private/ed/lib/libed_io.so(_ZNK2ed9ImageMask5beginEi+0x79)[0x7faeda9d4ee1]
/home/amigo/ros/kinetic/system/devel/lib/libed_perception_plugin_image_recognition.so(_ZN2ed10perception32PerceptionPluginImageRecognition11srvClassifyERN13ed_perception16ClassifyRequest_ISaIvEEERNS2_17ClassifyResponse_IS4_EE+0x65f)[0x7fae97dd1a97]
/home/amigo/ros/kinetic/system/devel/lib/libed_perception_plugin_image_recognition.so(_ZNK5boost4_mfi3mf2IbN2ed10perception32PerceptionPluginImageRecognitionERN13ed_perception16ClassifyRequest_ISaIvEEERNS5_17ClassifyResponse_IS7_EEEclEPS4_S9_SC_+0x76)[0x7fae97de2bd4]
/home/amigo/ros/kinetic/system/devel/lib/libed_perception_plugin_image_recognition.so(_ZN5boost3_bi5list3INS0_5valueIPN2ed10perception32PerceptionPluginImageRecognitionEEENS_3argILi1EEENS8_ILi2EEEEclIbNS_4_mfi3mf2IbS5_RN13ed_perception16ClassifyRequest_ISaIvEEERNSF_17ClassifyResponse_ISH_EEEENS0_5list2ISJ_SM_EEEET_NS0_4typeISQ_EERT0_RT1_l+0x87)[0x7fae97de18df]
/home/amigo/ros/kinetic/system/devel/lib/libed_perception_plugin_image_recognition.so(_ZN5boost3_bi6bind_tIbNS_4_mfi3mf2IbN2ed10perception32PerceptionPluginImageRecognitionERN13ed_perception16ClassifyRequest_ISaIvEEERNS7_17ClassifyResponse_IS9_EEEENS0_5list3INS0_5valueIPS6_EENS_3argILi1EEENSK_ILi2EEEEEEclISA_SD_EEbRT_RT0_+0x5d)[0x7fae97de03ed]
/home/amigo/ros/kinetic/system/devel/lib/libed_perception_plugin_image_recognition.so(_ZN5boost6detail8function21function_obj_invoker2INS_3_bi6bind_tIbNS_4_mfi3mf2IbN2ed10perception32PerceptionPluginImageRecognitionERN13ed_perception16ClassifyRequest_ISaIvEEERNSA_17ClassifyResponse_ISC_EEEENS3_5list3INS3_5valueIPS9_EENS_3argILi1EEENSN_ILi2EEEEEEEbSE_SH_E6invokeERNS1_15function_bufferESE_SH_+0x33)[0x7fae97dde9a2]
[ERROR] [1506452550.702311]: InvalidUserCodeError: Could not execute state 'INSPECT_SHELVES' of type '<challenge_storing_groceries.inspect_shelves.InspectShelves object at 0x7f7788930550>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/challenge_storing_groceries/src/challenge_storing_groceries/inspect_shelves.py", line 76, in execute
    entity_types_and_probs = self.robot.ed.classify(ids=segmented_entities.new_ids, types=config.OBJECT_TYPES)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/world_model_ed.py", line 327, in classify
    res = self._ed_classify_srv(ids=ids)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

[ERROR] [1506452550.702610]: Robot exited with <class 'smach.exceptions.InvalidUserCodeError'>,Could not execute state 'INSPECT_SHELVES' of type '<challenge_storing_groceries.inspect_shelves.InspectShelves object at 0x7f7788930550>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/challenge_storing_groceries/src/challenge_storing_groceries/inspect_shelves.py", line 76, in execute
    entity_types_and_probs = self.robot.ed.classify(ids=segmented_entities.new_ids, types=config.OBJECT_TYPES)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/world_model_ed.py", line 327, in classify
    res = self._ed_classify_srv(ids=ids)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
,<traceback object at 0x7f7793192248>
[INFO] [1506452550.702869]: Torso cancelling all goals on close
[INFO] [1506452550.703144]: left arm cancelling all goals on all arm-related ACs on close
[INFO] [1506452550.703520]: right arm cancelling all goals on all arm-related ACs on close
Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/challenge_storing_groceries/scripts/challenge_storing_groceries", line 11, in <module>
    startup(StoringGroceries)
  File "/home/amigo/ros/kinetic/system/src/robot_smach_states/src/robot_smach_states/util/startup.py", line 81, in startup
    outcome = executioner.execute()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: Could not execute state 'INSPECT_SHELVES' of type '<challenge_storing_groceries.inspect_shelves.InspectShelves object at 0x7f7788930550>': Traceback (most recent call last):
  File "/home/amigo/ros/kinetic/system/src/smach/src/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/amigo/ros/kinetic/system/src/challenge_storing_groceries/src/challenge_storing_groceries/inspect_shelves.py", line 76, in execute
    entity_types_and_probs = self.robot.ed.classify(ids=segmented_entities.new_ids, types=config.OBJECT_TYPES)
  File "/home/amigo/ros/kinetic/system/src/robot_skills/src/robot_skills/world_model_ed.py", line 327, in classify
    res = self._ed_classify_srv(ids=ids)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

ed: /usr/include/boost/thread/pthread/recursive_mutex.hpp:113: void boost::recursive_mutex::lock(): Assertion `!pthread_mutex_lock(&m)' failed.

**Comment by MatthijsBurgh** [comment]
I think this is the same issue as #29. This one is solved, so closing this one.
